### ISSUE TITLE
Kotlin Gradle Build issue

### ISSUE THREAD

**Issue by bobtheogre** [florent37/AnimatedWidgets#3]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':animated_widgets' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by florent37** [comment]
please try the `1.0.2`
