### ISSUE TITLE
RotationAnimatedWidget.tween only works for the first enabled switch

### ISSUE THREAD

**Issue by michaelroudnitski** [florent37/AnimatedWidgets#4]
### My code
```
RotationAnimatedWidget.tween(
          enabled: userOwesFriend,
          duration: Duration(milliseconds: 250),
          rotationDisabled: Rotation.deg(z: 0),
          rotationEnabled: Rotation.deg(z: 180, x: 180),
          curve: Curves.easeOut,
          child: IconButton(
            color: userOwesFriend
                ? Colors.redAccent
                : Theme.of(context).primaryColor,
            icon: Icon(Icons.swap_horizontal_circle),
            enableFeedback: true,
            tooltip: "Tap to change who owes who",
            highlightColor: Colors.transparent,
            splashColor: Colors.transparent,
            onPressed: () {
              setState(() {
                userOwesFriend = !userOwesFriend;
              });
            },
          ),
        ),
```

It works perfectly well for the first onPress event, the rotation is perfect. But, after this first onPress the animation never returns to the rotationDisabled state. Package does exactly what I need if that can be resolved so thanks for making it!

**Comment by pgfeng** [comment]
As for the question we are discussing now, do we find a solution?

**Comment by pgfeng** [comment]
At present, I do this, which can realize the reciprocating state animation.
`_open_status_1?RotationAnimatedWidget.tween(
                                  enabled: _open_status_1,
                                  duration: Duration(milliseconds: 250),
                                  rotationDisabled: Rotation.deg(z: -180),
                                  rotationEnabled: Rotation.deg(z: 0),
                                  child: Icon(Icons.arrow_drop_up,
                                      textDirection: TextDirection.rtl,
                                      size: rpx(32))): RotationAnimatedWidget.tween(
                                  enabled: !_open_status_1,
                                  duration: Duration(milliseconds: 250),
                                  rotationDisabled: Rotation.deg(z: 0),
                                  rotationEnabled: Rotation.deg(z: -180),
                                  child: Icon(Icons.arrow_drop_up,
                                      textDirection: TextDirection.rtl,
                                      size: rpx(32)))
`

**Comment by pgfeng** [comment]
目前，我正在执行此操作，可以实现往复状态动画。
`
_open_status_1
                              ? RotationAnimatedWidget.tween(
                                  enabled: _open_status_1,
                                  duration: Duration(milliseconds: 250),
                                  rotationDisabled: Rotation.deg(z: -180),
                                  rotationEnabled: Rotation.deg(z: 0),
                                  child: Icon(Icons.arrow_drop_up,
                                      textDirection: TextDirection.rtl,
                                      size: rpx(32)))
                              : RotationAnimatedWidget.tween(
                                  enabled: !_open_status_1,
                                  duration: Duration(milliseconds: 250),
                                  rotationDisabled: Rotation.deg(z: 0),
                                  rotationEnabled: Rotation.deg(z: -180),
                                  child: Icon(Icons.arrow_drop_up,
                                      textDirection: TextDirection.rtl,
                                      size: rpx(32)))

`

**Comment by pgfeng** [comment]
# At present, I do this, which can realize the reciprocating state animation.

`
_open_status_1
                              ? RotationAnimatedWidget.tween(
                                  enabled: _open_status_1,
                                  duration: Duration(milliseconds: 250),
                                  rotationDisabled: Rotation.deg(z: -180),
                                  rotationEnabled: Rotation.deg(z: 0),
                                  child: Icon(Icons.arrow_drop_up,
                                      textDirection: TextDirection.rtl,
                                      size: rpx(32)))
                              : RotationAnimatedWidget.tween(
                                  enabled: !_open_status_1,
                                  duration: Duration(milliseconds: 250),
                                  rotationDisabled: Rotation.deg(z: 0),
                                  rotationEnabled: Rotation.deg(z: -180),
                                  child: Icon(Icons.arrow_drop_up,
                                      textDirection: TextDirection.rtl,
                                      size: rpx(32)))
`
