### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by aopar75** [florent37/AnimatedWidgets#7]
Great package!.. Thanks a lot.
Just one question.. there is a way to autostart the animation?

Set 'enabled: true' does not work.. 

Thanks

**Comment by florent37** [comment]
What widget are you using ? Enabled:true should work

**Comment by florent37** [comment]
I just fixed the enabled:true for shake widget in the 1.0.6 

if it was not this widget, please re-open this ticket and send me the name of the widget :)

**Comment by aopar75** [comment]
Sorry, yes, was the shake one.. 
Thanks a lot for your work!

**Comment by florent37** [comment]
You're welcome 🥰
